from __future__ import annotations

from pathlib import Path
from tempfile import TemporaryDirectory
from zipfile import ZIP_DEFLATED, ZIP_STORED, ZipFile, ZipInfo

import pytest

from mindustry_agents.telemetry.artifact_provenance import jar_content_sha256


def _write_archive(
    path: Path,
    entries: list[tuple[str, bytes]],
    *,
    timestamp: tuple[int, int, int, int, int, int],
    compression: int,
) -> None:
    with ZipFile(path, "w") as archive:
        for name, content in entries:
            info = ZipInfo(name, timestamp)
            info.compress_type = compression
            archive.writestr(info, content)


def test_jar_content_digest_ignores_order_timestamp_and_compression():
    entries = [("b/B.class", b"class-b"), ("a/A.class", b"class-a")]
    with TemporaryDirectory() as directory:
        first = Path(directory) / "first.jar"
        second = Path(directory) / "second.jar"
        _write_archive(
            first,
            entries,
            timestamp=(2025, 1, 2, 3, 4, 6),
            compression=ZIP_STORED,
        )
        _write_archive(
            second,
            list(reversed(entries)),
            timestamp=(2026, 7, 23, 8, 10, 12),
            compression=ZIP_DEFLATED,
        )
        assert first.read_bytes() != second.read_bytes()
        assert jar_content_sha256(first) == jar_content_sha256(second)


def test_jar_content_digest_changes_with_name_or_content():
    with TemporaryDirectory() as directory:
        first = Path(directory) / "first.jar"
        second = Path(directory) / "second.jar"
        third = Path(directory) / "third.jar"
        _write_archive(
            first,
            [("a/A.class", b"one")],
            timestamp=(2026, 1, 1, 0, 0, 0),
            compression=ZIP_STORED,
        )
        _write_archive(
            second,
            [("a/A.class", b"two")],
            timestamp=(2026, 1, 1, 0, 0, 0),
            compression=ZIP_STORED,
        )
        _write_archive(
            third,
            [("b/A.class", b"one")],
            timestamp=(2026, 1, 1, 0, 0, 0),
            compression=ZIP_STORED,
        )
        assert jar_content_sha256(first) != jar_content_sha256(second)
        assert jar_content_sha256(first) != jar_content_sha256(third)


def test_mindustry_version_properties_ignores_only_volatile_build_time():
    first_properties = b"""#Autogenerated file. Do not modify.
#Thu Jul 23 08:18:35 AEST 2026
build=custom build
buildDate=July 23, 2026 08\\:18 am
commitHash=unknown
modifier=release
number=8
type=official
"""
    second_properties = first_properties.replace(
        b"#Thu Jul 23 08:18:35 AEST 2026",
        b"#Thu Jul 23 09:41:02 AEST 2026",
    ).replace(b"08\\:18 am", b"09\\:41 am")
    changed_version = second_properties.replace(b"number=8", b"number=9")
    with TemporaryDirectory() as directory:
        first = Path(directory) / "first.jar"
        second = Path(directory) / "second.jar"
        third = Path(directory) / "third.jar"
        for path, content in (
            (first, first_properties),
            (second, second_properties),
            (third, changed_version),
        ):
            _write_archive(
                path,
                [("version.properties", content)],
                timestamp=(2026, 1, 1, 0, 0, 0),
                compression=ZIP_STORED,
            )
        assert jar_content_sha256(first) == jar_content_sha256(second)
        assert jar_content_sha256(first) != jar_content_sha256(third)


def test_invalid_archive_is_rejected():
    with TemporaryDirectory() as directory:
        path = Path(directory) / "invalid.jar"
        path.write_bytes(b"not a zip")
        with pytest.raises(ValueError, match="invalid JAR/ZIP"):
            jar_content_sha256(path)
